# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
X = torch.rand(size=(7, 7))
X, X.shape

(tensor([[0.2854, 0.6128, 0.4677, 0.6728, 0.6702, 0.5036, 0.8775],
         [0.7953, 0.8823, 0.7089, 0.7116, 0.9356, 0.9692, 0.4512],
         [0.0035, 0.4771, 0.0173, 0.8339, 0.4977, 0.1367, 0.8409],
         [0.1463, 0.5667, 0.6083, 0.6598, 0.5889, 0.1796, 0.3562],
         [0.8102, 0.5092, 0.6776, 0.7084, 0.0364, 0.9561, 0.2708],
         [0.4751, 0.7023, 0.3152, 0.5303, 0.0978, 0.0090, 0.7819],
         [0.3422, 0.3430, 0.6257, 0.3951, 0.8630, 0.4740, 0.6371]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
X = torch.rand(size=(1, 7))
# Perform matrix multiplication
y = X @ X.T

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
X1 = torch.rand(2, 5)
torch.manual_seed(seed=RANDOM_SEED)
X2 = torch.rand(5, 2)

# Matrix multiply tensors
torch.matmul(X1, X2)

tensor([[0.5462, 0.8515],
        [1.1450, 1.9285]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [13]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device: {device}')

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.6977, 0.8000, 0.1610],
         [0.2823, 0.6816, 0.9152]], device='cuda:0'),
 tensor([[0.3971, 0.8742, 0.4194],
         [0.5529, 0.9527, 0.0362]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [19]:
# Perform matmul on tensor_A and tensor_B
tensor_C = tensor_A @ tensor_B.T
tensor_C, tensor_C.shape

(tensor([[1.0439, 1.1538],
         [1.0918, 0.8386]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
# Find max
torch.max(tensor_C), tensor_C.max()
# Find min
torch.min(tensor_C), tensor_C.min()

(tensor(0.8386, device='cuda:0'), tensor(0.8386, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [21]:
# Find arg max
torch.argmax(tensor_C), tensor_C.argmax()

# Find arg min
torch.argmin(tensor_C), tensor_C.argmin()

(tensor(3, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [24]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_squeeze = tensor.squeeze()

# Print out tensors and their shapes
tensor_squeeze, tensor_squeeze.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))